server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_java1234_mall?serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id生成规则：数据库id自增
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

weixin:
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
  appid: wxf503a70f5f45cbd2
  secret: feff78e86e4dfd6db133c4f8d214d7a3



bigTypeImagesFilePath: D://java1234-mall/bigTypeImgs/

productImagesFilePath: D://java1234-mall/productImgs/

swiperImagesFilePath: D://java1234-mall/swiperImgs/

productSwiperImagesFilePath: D://java1234-mall/productSwiperImgs/





