<%@ Page Title="" Language="C#" MasterPageFile="~/ParentPage1.Master" AutoEventWireup="true" CodeBehind="Adminview.aspx.cs" Inherits="WebApplication1.ShowUser" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1 class="auto-style2">用户表单查看和修改删除</h1>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1" Width="1130px" AutoGenerateColumns="False" DataKeyNames="Uid" AllowPaging="True" CellPadding="4" ForeColor="#333333" GridLines="None">
        <AlternatingRowStyle BackColor="White" />
        <Columns>
            <asp:BoundField DataField="Uid" HeaderText="账号" ReadOnly="True" SortExpression="Uid" >
            <ItemStyle HorizontalAlign="Center" />
            </asp:BoundField>
            <asp:BoundField DataField="Upwd" HeaderText="密码" SortExpression="Upwd" >
            <ItemStyle HorizontalAlign="Center" />
            </asp:BoundField>
            <asp:BoundField DataField="Uname" HeaderText="姓名" SortExpression="Uname" >
            <ItemStyle HorizontalAlign="Center" />
            </asp:BoundField>
            <asp:BoundField DataField="Utype" HeaderText="用户类型" SortExpression="Utype" >
            <ItemStyle HorizontalAlign="Center" />
            </asp:BoundField>
            <asp:BoundField DataField="Uqq" HeaderText="用户QQ" SortExpression="Uqq" >
            <ItemStyle HorizontalAlign="Center" />
            </asp:BoundField>
        </Columns>
        <EditRowStyle BackColor="#2461BF" />
        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#EFF3FB" />
        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#F5F7FB" />
        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
        <SortedDescendingCellStyle BackColor="#E9EBEF" />
        <SortedDescendingHeaderStyle BackColor="#4870BE" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:lizifanConnectionString %>" DeleteCommand="DELETE FROM [User] WHERE [Uid] = @original_Uid AND [Upwd] = @original_Upwd AND [Uname] = @original_Uname AND [Utype] = @original_Utype AND [Uqq] = @original_Uqq" InsertCommand="INSERT INTO [User] ([Uid], [Upwd], [Uname], [Utype], [Uqq]) VALUES (@Uid, @Upwd, @Uname, @Utype, @Uqq)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [User]" UpdateCommand="UPDATE [User] SET [Upwd] = @Upwd, [Uname] = @Uname, [Utype] = @Utype, [Uqq] = @Uqq WHERE [Uid] = @original_Uid AND [Upwd] = @original_Upwd AND [Uname] = @original_Uname AND [Utype] = @original_Utype AND [Uqq] = @original_Uqq">
        <DeleteParameters>
            <asp:Parameter Name="original_Uid" Type="String" />
            <asp:Parameter Name="original_Upwd" Type="String" />
            <asp:Parameter Name="original_Uname" Type="String" />
            <asp:Parameter Name="original_Utype" Type="String" />
            <asp:Parameter Name="original_Uqq" Type="String" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="Uid" Type="String" />
            <asp:Parameter Name="Upwd" Type="String" />
            <asp:Parameter Name="Uname" Type="String" />
            <asp:Parameter Name="Utype" Type="String" />
            <asp:Parameter Name="Uqq" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="Upwd" Type="String" />
            <asp:Parameter Name="Uname" Type="String" />
            <asp:Parameter Name="Utype" Type="String" />
            <asp:Parameter Name="Uqq" Type="String" />
            <asp:Parameter Name="original_Uid" Type="String" />
            <asp:Parameter Name="original_Upwd" Type="String" />
            <asp:Parameter Name="original_Uname" Type="String" />
            <asp:Parameter Name="original_Utype" Type="String" />
            <asp:Parameter Name="original_Uqq" Type="String" />
        </UpdateParameters>
</asp:SqlDataSource>
</asp:Content>
