<?xml version="1.0" encoding="utf-8"?><Database Name="lizifan" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=lizifan;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="lizifanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="Uid" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Upwd" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Uname" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Utype" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Uqq" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Picture" Member="Picture">
    <Type Name="Picture">
      <Column Name="Pid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sname" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Sphone" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Pic" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Information" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="explaination" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>